config/routes.rb
MyAlbum::Application.routes.draw do
  if Rails.env.development?
    mount Resque::Server.new, :at => "/resque"
  end
  match 'login' => 'users#login', :as => :login
  match 'logout' => 'users#logout', :as => :logout
  match 'signup' => 'users#signup', :as => :signup
  resources :p_albums

  resources :upload_photos do
    resources :comments
  end
  
  
  resources :users
  
  resources :homes, :only => [:index, :create, :new]

  get "home/index"
  
  root :to => "p_albums#new"

end

app/models/upload_photo.rb
# encoding: utf-8 
class UploadPhoto
  include Mongoid::Document
  include Mongoid::Timestamps

  field :title
  field :description
  field :photoURL
  field :albumBelongTo
  field :avatar, type: String

  belongs_to :p_album
  has_many :comments, dependent: :delete
 
  validates_presence_of :photoURL, :message => "图像地址不能为空"
end

app/controllers/upload_photos_controller.rb
# encoding: utf-8 
class UploadPhotosController < ApplicationController
  # GET /upload_photos
  # GET /upload_photos.json
  before_filter :login_required
  
  before_filter :find_photo, :only => [:show, :edit, :update, :destroy]

  def index
    @upload_photos = UploadPhoto.where(user_id: current_user.id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @upload_photos }
    end
  end

  # GET /upload_photos/1
  # GET /upload_photos/1.json
  def show
    @comment = @upload_photo.comments.build
  end

  # GET /upload_photos/new
  # GET /upload_photos/new.json
  def new
    @action_name ="上传"
    @upload_photo = UploadPhoto.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @upload_photo }
    end
  end

  # GET /upload_photos/1/edit
  def edit
    @action_name ="修改"
  end

  # POST /upload_photos
  # POST /upload_photos.json
  def create
    album = find_album(params[:upload_photo][:albumBelongTo]).first
    options = params[:upload_photo]
    @upload_photo = album.upload_photos.create(
        title: options[:title],
        description: options[:description],
        photoURL: uploadPhoto(options[:photoURL]),
        albumBelongTo: options[:albumBelongTo],
        user_id: current_user.id
    )
    respond_to do |format|
      format.html { redirect_to @upload_photo, :notice => '照片上传成功。' }
      format.json { render :json => @upload_photo, :status => :created, :location => @upload_photo }
    end
  end

  # PUT /upload_photos/1
  # PUT /upload_photos/1.json
  def update
    if @upload_photo.user_id == current_user.id
      respond_to do |format|
        if @upload_photo.update_attributes(params[:upload_photo])
          format.html { redirect_to @upload_photo, :notice => '照片信息已经成功更新。' }
          format.json { head :no_content }
          #end
        else
          format.html { render :action => "edit" }
          format.json { render :json => @upload_photo.errors, :status => :unprocessable_entity }
        end
      end
    else
       redirect_to @upload_photo, :notice => '没有权限！'
    end
  end

  # DELETE /upload_photos/1
  # DELETE /upload_photos/1.json
  def destroy
    @upload_photo.destroy
    delPhoto(@upload_photo.photoURL)

    respond_to do |format|
      format.html { redirect_to upload_photos_url }
      format.json { head :no_content }
    end
  end
  
  def find_photo
    @upload_photo = UploadPhoto.find(params[:id])
  end
  
  def uploadPhoto(file)
    fileName=file.original_filename
    if !fileName.empty?
      FileUtils.mkdir($uploadFolder) unless File.exist?($uploadFolder)
      File.open($uploadFolder+"/#{fileName}", "wb") do |f|
        f.write(file.read)
      end
      return fileName
    end
  end
  
  def delPhoto(filename)
      FileUtils.rm($uploadFolder+"/"+filename) unless filename.empty?
  end
  
  def checkFileType(fileName)
    if fileName =~ /.jpg/
      return true
    else
      return false
    end
  end
  
  def find_album(album_name)
    return PAlbum.where(album_name: album_name)
  end
end

app/helpers/upload_photos_helper.rb
module UploadPhotosHelper
end

app/views/upload_photos/_form.html.haml
= simple_form_for(@upload_photo, :html => { :multipart => true }) do |f|
  - if @upload_photo.errors.any?
    #error_explanation
      %2h2= pluralize(@upload_photo.errors.count, "个错误")

      %ul
      - @upload_photo.errors.full_messages.each do |msg|
        %li= msg
  .field
    = f.label :标题
    = f.text_field :title
  .field
    = f.label :照片描述
    = f.text_area :description, :rows =>6
  .field
    - if @upload_photo.photoURL.nil?
      = f.file_field("photoURL")
    - else
      - photoURL = @upload_photo.photoURL
      = image_tag("upload/"+photoURL, :width => "100")
  .field
    = f.label :选择相册
    - arrAlbums = allAlbum
    = f.select(:albumBelongTo, options_for_select(arrAlbums))
    %span= link_to "或者创建新相册", new_p_album_path
  .actions
    = f.submit @action_name, :class => 'btn btn-primary'

app/views/upload_photos/edit.html.haml
%h2编辑照片

= render 'form'

= link_to '详细信息', @upload_photo |
= link_to '后退', upload_photos_path

app/views/upload_photos/index.html.haml
%h2所有照片
.image_search 
  = text_field_tag "images_search_box", "", {placeholder: "搜索", class: "image_search_box"}

%table
  %tr
    %th标题
    %th照片描述
    %th照片预览
    %th所属相册
    %th{ :cols => "3" }操作
  - @upload_photos.each do |upload_photo|
    %tr
      %td= upload_photo.title
      %td= upload_photo.description
      %td.image= link_to(image_tag("upload/"+upload_photo.photoURL, :width => "100" ), upload_photo)
      %td= upload_photo.albumBelongTo
      %td= link_to '显示', upload_photo
      %td= link_to '编辑', edit_upload_photo_path(upload_photo)
      %td= link_to '删除', upload_photo, :confirm => '确定删除?', :method => :delete
%br

= link_to '上传新照片', new_upload_photo_path
:javascript
  $(document).ready(function(){
    var all_photos = "#{@upload_photos.map{|photo| [photo.id, photo.title]}}";
  })

app/views/upload_photos/new.html.haml
%h1上传新照片

= render 'form'

= link_to '后退', upload_photos_path

app/views/upload_photos/show.html.erb
<p id="notice"><%= notice %></p>

  <div id="photo">
    <div>标题：<%= @upload_photo.title %></div>
    <div>描述：<%= @upload_photo.description %></div>
    <div id="image">预览：<a href="/assets/upload/<%= @upload_photo.photoURL %>" title="点击查看大图"><%= image_tag("upload/"+@upload_photo.photoURL, :width => "150", :class => "image_border") %></a></div>
    <div>所属相册：<%= @upload_photo.albumBelongTo %></div>
  </div>
  
  <div id="comments">
    <% if @upload_photo.comments.exists? %>
      <h3>所有评论</h3>
      <%= render @upload_photo.comments.select(&:persisted?) %>
    <% else %>
      <h3>暂时没有评论！</h3>
    <% end %>
  </div>
    <hr />  
    <%= render "comments/form"%>

<% if @upload_photo.user_id == current_user.id %>
<%= link_to '编辑', edit_upload_photo_path(@upload_photo) %>|
<% end %>
<%= link_to '后退', upload_photos_path %>
<script type="text/javascript">
  $("#notice").fadeOut(2000);
</script>

app/views/upload_photos/show.html.haml
.alert.alert-success
#photo
  %div 标题：
  = @upload_photo.title
  %div 描述：
  = @upload_photo.description
  #image预览：
  = link_to(image_tag("upload/"+@upload_photo.photoURL, :width => "150", :class => "image_border"), "/assets/upload/#{@upload_photo.photoURL} ", :title => "点击查看大图")
  %div 所属相册：
  = @upload_photo.albumBelongTo
#comments
  - if @upload_photo.comments.exists?
    %h3 所有评论
    = render @upload_photo.comments.scoped.order_by("created_at ASC")
  - else
    %h3 暂时没有评论！
  %hr  
  = render "comments/form"
  - if @upload_photo.user_id == current_user.id
    = link_to '编辑', edit_upload_photo_path(@upload_photo)
    |
    = link_to '后退', upload_photos_path