config/routes.rb
MyAlbum::Application.routes.draw do
  if Rails.env.development?
    mount Resque::Server.new, :at => "/resque"
  end
  match 'login' => 'users#login', :as => :login
  match 'logout' => 'users#logout', :as => :logout
  match 'signup' => 'users#signup', :as => :signup
  resources :p_albums

  resources :upload_photos do
    resources :comments
  end
  
  
  resources :users
  
  resources :homes, :only => [:index, :create, :new]

  get "home/index"
  
  root :to => "p_albums#new"

end

app/models/p_album.rb
# encoding: utf-8
class PAlbum
  include Mongoid::Document
  include Mongoid::Timestamps

  field :album_name
  field :album_description

  validates_presence_of :album_name, :presence => true, :message => "不能为空"
  validates_uniqueness_of :album_name, :uniqueness => true, :message => "必须唯一"

  has_many :upload_photos, dependent: :delete
  belongs_to :user
end

app/controllers/p_albums_controller.rb
# encoding: utf-8 
class PAlbumsController < ApplicationController
  # GET /p_albums
  # GET /p_albums.json
  before_filter :login_required
  
  def index
    @p_albums = PAlbum.where(user_id: current_user.id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @p_albums }
    end
  end

  # GET /p_albums/1
  # GET /p_albums/1.json
  def show
    @p_album = PAlbum.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @p_album }
    end
  end

  # GET /p_albums/new
  # GET /p_albums/new.json
  def new
    @p_album = PAlbum.new
    @action_name ="创建"

    # respond_to do |format|
    #   format.html # new.html.erb
    #   format.json { render :json => @p_album }
    # end
  end

  # GET /p_albums/1/edit
  def edit
    @p_album = PAlbum.find(params[:id])
    @action_name ="修改"
  end

  # POST /p_albums
  # POST /p_albums.json
  def create
    @p_album = PAlbum.new(
      album_name: params[:p_album][:album_name],
      album_description: params[:p_album][:album_description],
      user_id: current_user.id
    )

    respond_to do |format|
      if @p_album.save
        format.html { redirect_to @p_album, :notice => '成功创建新相册' }
        format.json { render :json => @p_album, :status => :created, :location => @p_album }
      else
        format.html { render :action => "new" }
        format.json { render :json => @p_album.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /p_albums/1
  # PUT /p_albums/1.json
  def update
    @p_album = PAlbum.find(params[:id])

    respond_to do |format|
      if @p_album.update_attributes(params[:p_album])
        format.html { redirect_to @p_album, :notice => '成功修改相册信息' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @p_album.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /p_albums/1
  # DELETE /p_albums/1.json
  def destroy
    @p_album = PAlbum.find(params[:id])
    _delRecord(@p_album.album_name)
    @p_album.destroy

    respond_to do |format|
      format.html { redirect_to p_albums_url }
      format.json { head :no_content }
    end
  end
  
  def _delRecord(value)
    @photos=UploadPhoto.where(albumBelongTo: value)
    @photos.each do |photo|
      FileUtils.rm($uploadFolder+"/"+photo.photoURL)
      photo.destroy
    end
  end
  
end

app/helpers/p_albums_helper.rb
module PAlbumsHelper
end

app/views/p_albums/_form.html.haml
= form_for(@p_album) do |f|
  - if @p_album.errors.any?
    #error_explanation
      %2h2= pluralize(@p_album.errors.count, "个错误")

      %ul
      - @p_album.errors.full_messages.each do |msg|
        %li= msg
  #displayAlbum
    %h2已有的相册
    #albumList
      - allAlbum
      - @albums.each do |p_album|
      - album_name=p_album.album_name
        #albumItem.albumItem
          - photos = UploadPhoto.where(albumBelongTo: album_name)
          
          - if photos.count==0
            = image_tag("icon/no_photo_s.png")
            %br
          - elsif
            - photoFirst=photos.first
            .image= link_to image_tag("upload/"+photoFirst.photoURL, :width => "100"), p_album
          %br
          %span#albumName
          = album_name
          &nbsp;共&nbsp;
          = photos.count
          张
          %br
          %span#albumOpr.hide
          = link_to '删除', p_album, :confirm => '确定删除此相册?注意：删除此相册的同时，此相册下的所有照片也会被删除！', :method => :delete
          = link_to '修改', edit_p_album_path(p_album)
  .field
    = f.label :相册名称
    %br
    = f.text_field :album_name
  .field
    = f.label :相册描述
    %br
    = f.text_area :album_description, :rows => 6
  .actions
    = f.submit @action_name, :class => 'btn btn-primary'

app/views/p_albums/edit.html.haml
%h2修改相册信息

= render 'form'

= link_to '详细信息', @p_album

app/views/p_albums/index.html.haml
- if flash[:message]
  .alert.alert-error
    = flash[:message]
%h2所有相册
= link_to '创建新相册+', new_p_album_path
%table
  %tr
    %th相册名称
    %th相册描述
    %th{:cols =>"3"}操作
  - @p_albums.each do |p_album|
    %tr
      %td
        = p_album.album_name
      %td
        = p_album.album_description
      %td
        = link_to '详细', p_album
      %td
        = link_to '修改', edit_p_album_path(p_album)
      %td
        = link_to '删除', p_album, :confirm => '确定删除此相册?', :method => :delete

app/views/p_albums/new.html.haml
%h2新建相册

= render 'form'

app/views/p_albums/show.html.haml
.alert.alert-success
  = notice
  %button.close{"data-dismiss" => "alert", :type => "button"} ×
= link_to '修改', edit_p_album_path(@p_album)
|
\#{link_to '后退', p_albums_path}
%table
  %tr
    %th 相册名称
    %th 相册描述
    %th 本相册中所有照片
  %tr
    %td= @p_album.album_name
    %td= @p_album.album_description
    %td.images
      - @photos=UploadPhoto.where(albumBelongTo: @p_album.album_name)
      - @photos.each do |photo|
        = link_to image_tag("upload/"+photo.photoURL, :width => "100"), photo