config/routes.rb
MyAlbum::Application.routes.draw do
  if Rails.env.development?
    mount Resque::Server.new, :at => "/resque"
  end
  match 'login' => 'users#login', :as => :login
  match 'logout' => 'users#logout', :as => :logout
  match 'signup' => 'users#signup', :as => :signup
  resources :p_albums

  resources :upload_photos do
    resources :comments
  end
  
  
  resources :users
  
  resources :homes, :only => [:index, :create, :new]

  get "home/index"
  
  root :to => "p_albums#new"

end

app/models/comment.rb
# encoding: utf-8 
class Comment
  include Mongoid::Document
  include Mongoid::Timestamps

  field :text
  field :upload_photo_id
  field :post_time
  field :user_id

  belongs_to :upload_photo
  
  validates_presence_of :text, :message => "不能为空"
end

app/controllers/comments_controller.rb
# encoding: utf-8 
require 'RedCloth'

class CommentsController < ApplicationController
  before_filter :find_photo
  before_filter :format_time

  def create 
    @comment = @upload_photo.comments.new(params[:comment])
    @comment.update_attribute(:user_id, current_user.id)
    respond_to do |format|
      if @comment.save
        flash[:notice] = "评论保存成功！"
        format.html { redirect_to @upload_photo }
        format.js
        format.json { render :json => @comment } # this
      else
        flash[:alert] = "无法保存评论！"
        format.html { redirect_to @upload_photo }
        format.xml { render :xml => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def edit
    @comment = @upload_photo.comments.find(params[:id])
    @action_name = "修改"
  end
  
  def update
    @comment = @upload_photo.comments.find(params[:id])
    if @comment.update_attributes(params[:comment])
      flash[:notice] = "评论成功更新"
      respond_to do |format|
        format.html { redirect_to @upload_photo }
        format.js
      end
    else
      respond_to do |format|
        redirect_to @upload_photo
      end
    end
  end 
  
  def destroy
    @comment = @upload_photo.comments.find(params[:id])
    @comment.destroy
    redirect_to @upload_photo

    # respond_to do |format|

    #   format.html { redirect_to @upload_photo }
    #   format.js
    # end
  end
  
  private
  
    def find_photo
      @upload_photo = UploadPhoto.find(params[:upload_photo_id])
      @action_name ="创建"
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.haml
%hr{:style => "border: dotted 0.5px"}
= div_for(comment) do
	%div{:style => "float: left"}= image_tag ("icon/avatar.png"), :class => "avatar"
	%div{:style => "margin-left: 5em"}
		%h4
			= link_to User.find(comment.user_id).name, user_path(comment.user_id)
			发表于：
			= comment.created_at.strftime("%Y-%m-%d %H:%M:%S")
	%div{:style => "margin-left: 5em"}
		= RedCloth.new(comment.text)
		- if current_user.id == comment.user_id
			%br
			= link_to "编辑", edit_upload_photo_comment_path(@upload_photo, comment)
			&nbsp;&nbsp;&nbsp;&nbsp;
			= link_to "删除", [@upload_photo, comment], :method => :delete

app/views/comments/_form.html.erb
<strong><%= @action_name %>评论</strong>

	<%= form_for ([@upload_photo, @comment]) do |f|%>

	<p>
	<%= f.label :text, "评论内容："%>
	<%= f.text_area :text, :rows => 6 %>
	</p>
	<div class="actions"><%= f.submit @action_name || "提交" %></div>
	<% end %>


<%
	if @action_name == nil
%>
<script type="text/javascript">
	$("#new_comment").attr("data-remote") = true;
</script>
<% else %>
<script type="text/javascript">
	$("form").removeAttr("data-remote");
</script>
<% end %>

app/views/comments/_form.html.haml
%strong
  = @action_name
  评论

- if @action_name == nil
  - @action_name = "提交"
  = simple_form_for([@upload_photo, @comment], remote: true) do |f|
    %div
      = f.label :text, "评论内容："
      = f.text_area :text, :rows => 6
      .actions
        = f.submit @action_name, :class => 'btn btn-primary'
- elsif
  = simple_form_for([@upload_photo, @comment]) do |f|
    %div
      = f.label :text, "评论内容："
      = f.text_area :text, :rows => 6
    .actions
      = f.submit @action_name, :class => 'btn btn-primary'

app/views/comments/create.js.erb
<% if @comment.errors.empty? %>
  $('#comments>h3').text('所有评论');
  $('<%= escape_javascript(render :partial => 'comment', :object => @comment) %>').hide().insertAfter($('#comments>h3')).fadeIn('fast');
<% else %>
  $('<span class="error-message"><%= escape_javascript(@comment.errors.full_messages.join(',')) %></span>');
<% end %>

app/views/comments/edit.html.haml
%h2 修改评论
= render "form"

app/views/comments/show.html.haml
%h2 评论:
= render "form"