config/routes.rb
MyAlbum::Application.routes.draw do
  if Rails.env.development?
    mount Resque::Server.new, :at => "/resque"
  end
  match 'login' => 'users#login', :as => :login
  match 'logout' => 'users#logout', :as => :logout
  match 'signup' => 'users#signup', :as => :signup
  resources :p_albums

  resources :upload_photos do
    resources :comments
  end
  
  
  resources :users
  
  resources :homes, :only => [:index, :create, :new]

  get "home/index"
  
  root :to => "p_albums#new"

end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "MyAlbum"
    = javascript_include_tag "application", :media => "all"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
  %body{:onload => "_init();"}
    #log
    #content
      .nav{:style => "float:right"}
        %p
          - if current_user.nil?
            = link_to("注册", "/signup")
            |
            = link_to("登录", "/login")
          - else
            当前用户
            = link_to(current_user.to_s, current_user)
            |
            =link_to("退出", '/logout')
      %div{:style => "height:80px;padding:0;margin:0;"}
        .myTabUI
          %ul.albumTabs
            %li#album.current   相册管理  
            %li#photo   照片管理  
        #album.album.show
          %li= link_to "添加相册", new_p_album_path, :id => "ahover"
          %li= link_to "管理相册", p_albums_path
        #photo.photo.hide
          %li= link_to "上传照片", new_upload_photo_path
          %li= link_to '管理照片', upload_photos_path
          %li 查询照片
      - if flash[:message]
        .alert.alert-success
          %button.close{"data-dismiss" => "alert", :type => "button"} &times;
          = flash[:message]
      - elsif flash[:error]
        .alert.alert-error
          %button.close{"data-dismiss" => "alert", :type => "button"} &times;
          = flash[:error]
      = yield
      - unless current_user.nil?
        %div= link_to "查看所有用户>>", users_path
    #foot Copyright©2010-2012 版权所有

app/views/layouts/fluid.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "MyAlbum"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")

  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="#") MyAlbum
          .container.nav-collapse
            %ul.nav
              %li= link_to "Link 1", "/path1"
              %li= link_to "Link 2", "/path2"
              %li= link_to "Link 3", "/path3"

    .container

      .row
        .span9
          = bootstrap_flash
          = yield
        .span3
          .well.sidebar-nav
            %h3 Sidebar
            %ul.nav.nav-list
              %li.nav-header Sidebar
              %li= link_to "Link 1", "/path1"
              %li= link_to "Link 2", "/path2"
              %li= link_to "Link 3", "/path3"
    
      %footer
        %p &copy; Company 2012
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/layouts/head.html.haml
- content_for :head do
%pHello, Rails!